#!/bin/bash

## Instali ffmpeg kaj aliajn dependojn:
apt update && sudo apt upgrade -y
apt-get install ffmpeg libmariadb3 libpq5 libmicrohttpd12 python3-pip python3-dev libssl-dev libcurl4-openssl-dev libjpeg-dev libz-dev python3-boto3
apt-get install ssh curl motion ffmpeg v4l-utils -y

## Instali motion:
wget http://ftp.cn.debian.org/debian/pool/main/libj/libjpeg-turbo/libjpeg62-turbo_2.0.5-2_amd64.deb
dpkg -i libjpeg62-turbo_2.0.5-2_amd64.deb
wget https://github.com/Motion-Project/motion/releases/download/release-4.3.2/buster_motion_4.3.2-1_amd64.deb
dpkg -i buster_motion_4.3.2-1_amd64.deb
## Instalu motioneye.eo:
pip3 install .


## krei agordon kaj dosierujojn:
mkdir -p /etc/motioneye
if [ ! -f /etc/motioneye/motioneye.conf ]
then
   cp /usr/local/share/motioneye/extra/motioneye.conf.sample /etc/motioneye/motioneye.conf
fi
mkdir -p /var/lib/motioneye
chown -R motion.motion /etc/motioneye /var/lib/motioneye

## krei la servon:
if [ ! -f /etc/systemd/system/motioneye.service ]
then
  cp /usr/local/share/motioneye/extra/motioneye.systemd-unit-local /etc/systemd/system/motioneye.service
fi
systemctl daemon-reload
systemctl enable motioneye
systemctl start motioneye
